# Generated by Django 3.1.1 on 2020-10-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_item_time_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='current_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timecapsule',
            name='current_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
