# Generated by Django 3.2 on 2021-04-28 02:20

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_extraitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196)),
                ('json_data', models.JSONField()),
                ('editor', django_quill.fields.QuillField()),
            ],
        ),
    ]
