# Generated by Django 3.2 on 2021-04-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_quilleditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quilleditor',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='integer_field',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='item_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoapp.item'),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='simple_choices',
            field=models.PositiveIntegerField(choices=[(0, 'Choice1'), (1, 'Choice2'), (2, 'Choice3'), (3, 'Choice4')], null=True),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='textarea',
            field=models.TextField(null=True),
        ),
    ]
