# Generated by Django 3.2 on 2021-04-28 15:57

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_auto_20210428_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='quilleditor',
            name='checkbox',
            field=models.BooleanField(default=True, help_text='Checkbox With helptext', null=True),
        ),
        migrations.AddField(
            model_name='quilleditor',
            name='checkbox2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quilleditor',
            name='editor',
            field=django_quill.fields.QuillField(help_text='Help text'),
        ),
        migrations.AlterField(
            model_name='quilleditor',
            name='item_fk',
            field=models.ForeignKey(help_text='Item FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoapp.item'),
        ),
        migrations.AlterField(
            model_name='quilleditor',
            name='title',
            field=models.CharField(help_text='Title Help Text', max_length=196),
        ),
    ]
